///////////////////////////////////////////////////
/// ® March 2013 =BTC= Muttley & =BTC= Giallustio//	
/// Visit us: www.blacktemplars.altervista.org   //
///////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
///////// WEAPONS CLIENT SIDE AMMO BOX ///////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
BTC_ammo_cont = 
	[
		[ 	//Select 0	//Weapons
			//NATO Weapons
			["srifle_GM6_SOS_F", 1],
			["srifle_LRR_SOS_F", 1],
			["LMG_Mk200_F", 1],
			["LMG_Zafir_F", 1],
			["arifle_MXC_F", 1],
			["arifle_MXM_F", 1],
			["arifle_MX_GL_F", 1],
			["arifle_MX_SW_F", 1],
			["arifle_MX_F", 1],
			["arifle_MXM_Hamr_point_gripod_F", 1],
			["srifle_EBR_F", 1],  
			["arifle_TRG20_F", 1],
			["arifle_TRG21_F", 1],
			["arifle_TRG21_GL_F", 1],
			["arifle_SDAR_F", 1],
			["arifle_Mk20_F", 1],
			["arifle_Mk20_GL_F", 1],
			["arifle_Mk20C_F", 1],
			["SMG_01_F", 1],
			// Pistols
			["hgun_P07_F", 1],
			["hgun_P07_snds_F", 1],
			["hgun_ACPC2_F", 1],
			["hgun_ACPC2_snds_F", 1],
			////Support Items
			["Binocular", 1],
			["Rangefinder", 1], 
			["laserdesignator", 1], 
			["Laserbatteries", 1],
			["FirstAidKit", 1],
			["ItemCompass", 1],
			["ItemGPS", 1],
			["ItemMap", 1],
			["ItemRadio", 1],
			["ItemWatch", 1],
			["MineDetector", 1],
			["B_UavTerminal", 1],
			["O_UavTerminal", 1],
			["I_UavTerminal", 1],
			////Attachments
			["acc_flashlight", 1],
			["acc_pointer_IR", 1],
			["muzzle_snds_B", 1],
			["muzzle_snds_H", 1],
			["muzzle_snds_H_MG", 1],
			["muzzle_snds_L", 1],
			["muzzle_snds_M", 1],
			["optic_Aco", 1],
			["optic_ACO_grn", 1],
			["optic_Arco", 1],
			["optic_Hamr", 1],
			["optic_Holosight", 1],
			["optic_Holosight_smg", 1],
			["optic_MRCO", 1],
			["optic_SOS", 1],
			["optic_Nightstalker", 1],
			["optic_NVS", 1],
			["optic_tws", 1],
			["optic_tws_mg", 1]
			
		],
		[	//Select 1   ////Ammo
			["20Rnd_762x51_Mag", 10],
			["30Rnd_65x39_caseless_mag", 10],
			["30Rnd_65x39_caseless_green_mag_Tracer", 10],
			["30Rnd_65x39_caseless_mag_Tracer", 10],
			["30Rnd_556x45_Stanag_Tracer_Red", 10],
			["100Rnd_65x39_caseless_mag", 10],
			["100Rnd_65x39_caseless_mag_Tracer", 10],
			["30Rnd_556x45_Stanag", 10],
			["20Rnd_556x45_UW_mag", 10],
			["16Rnd_9x21_Mag", 10],
			["30Rnd_65x39_case_mag", 10],
			["30Rnd_65x39_case_mag_Tracer", 10],
			["30Rnd_45ACP_Mag_SMG_01", 10],
			["30Rnd_45ACP_Mag_SMG_01_Tracer_Green", 10], 
			["200Rnd_65x39_cased_Box", 10],
			["200Rnd_65x39_cased_Box_Tracer", 10],
			["150Rnd_762x51_Box", 10],
			["150Rnd_762x51_Box_Tracer", 10],
			["5Rnd_127x108_Mag", 10],
			["7Rnd_408_Mag", 10]
		],
		[	//Select 2	// LAUNCHERS
			["launch_NLAW_F", 1],  
			["launch_RPG32_F", 1],
			["launch_B_Titan_short_F", 1],
			["launch_B_Titan_F", 1],
			["launch_I_Titan_short_F", 1],
			["launch_I_Titan_F", 1],
			["NLAW_F", 5],
			["RPG32_F", 5],
			["RPG32_HE_F", 5],
			["RPG32_AA_F", 5],
			["Titan_AA", 5],
			["Titan_AP", 5],
			["Titan_AT", 5]
		],
		[ 	//Select 3 
			////Grenade explosive Ammo
			["UGL_FlareWhite_F", 10],
			["UGL_FlareGreen_F", 10],
			["UGL_FlareRed_F", 10],
			["UGL_FlareYellow_F ", 10],
			["UGL_FlareCIR_F", 10],
			["1Rnd_HE_Grenade_shell", 10],
			["1Rnd_Smoke_Grenade_shell", 10],
			["1Rnd_SmokeRed_Grenade_shell", 10],
			["1Rnd_SmokeGreen_Grenade_shell", 10],
			["1Rnd_SmokeBlue_Grenade_shell", 10],
			["3Rnd_HE_Grenade_shell", 10],
			["3Rnd_UGL_FlareWhite_F", 10],
			["3Rnd_UGL_FlareGreen_F", 10],
			["3Rnd_UGL_FlareRed_F", 10],
			["3Rnd_UGL_FlareYellow_F", 10],
			["3Rnd_UGL_FlareCIR_F", 10],
			["3Rnd_Smoke_Grenade_shell", 10],
			["3Rnd_SmokeRed_Grenade_shell", 10],
			["3Rnd_SmokeGreen_Grenade_shell", 10],
			["3Rnd_SmokeBlue_Grenade_shell", 10],
			////Explosives
			["APERSBoundingMine_Range_Mag", 10],
			["APERSMine_Range_Mag", 10],
			["ATMine_Range_Mag", 10],
			["Chemlight_blue", 10],
			["Chemlight_green", 10],
			["Chemlight_red", 10],
			["Chemlight_yellow", 10],
			["ClaymoreDirectionalMine_Remote_Mag", 10],
			["DemoCharge_Remote_Mag", 10],
			["HandGrenade", 10],
			//["HandGrenade_Stone", 10],
			["MiniGrenade", 10],
			["SatchelCharge_Remote_Mag", 10],
			["SLAMDirectionalMine_Wire_Mag", 10],
			["SmokeShell", 10],
			["SmokeShellRed", 10],
			["SmokeShellGreen", 10],
			["SmokeShellBlue", 10]
		],
		[ //Select 4 ////Helmets/HATS
			["H_Cap_blu", 1],
			["H_Cap_brn_SERO", 1],
			["H_Cap_headphones", 1],
			["H_Cap_red", 1],
			["H_HelmetB", 1],
			["H_HelmetB_light", 1],
			["H_HelmetB_paint", 1],
			["H_HelmetB_plain_blk", 1],
			["H_HelmetB_plain_mcamo", 1],
			["H_PilotHelmetFighter_B", 1],
			["H_PilotHelmetFighter_I", 1],
			["H_PilotHelmetHeli_B", 1],
			["H_PilotHelmetHeli_I", 1],
			["H_HelmetO_ocamo", 1],
			["H_HelmetSpecB", 1],
			["H_HelmetSpecB_blk", 1],
			["H_HelmetSpecB_paint1", 1],
			["H_HelmetSpecB_paint2", 1],
			["H_HelmetIA", 1],
			["H_HelmetIA_camo", 1],
			["H_HelmetIA_net", 1],
			["H_MilCap_blue", 1],
			["H_HelmetCrew_B", 1],
			["H_HelmetCrew_I", 1],
			["H_HelmetCrew_O", 1],
			["H_Cap_blu_POLICE", 1],
			["H_Cap_brn_SPECOPS", 1],
			["H_MilCap_mcamo", 1],
			["H_MilCap_ocamo", 1],
			["H_PilotHelmetHeli_O", 1],

			////Clothing
			["U_B_CombatUniform_mcam", 1],
			["U_B_CombatUniform_mcam_tshirt", 1],
			["U_B_CombatUniform_mcam_vest", 1],
			["U_B_CombatUniform_mcam_worn", 1],
			["U_B_CombatUniform_sgg", 1],
			["U_B_CombatUniform_sgg_vest", 1],
			["U_B_CombatUniform_wdl", 1],
			["U_B_CombatUniform_wdl_tshirt", 1],
			["U_B_CombatUniform_wdl_vest", 1],
			["U_B_GhillieSuit", 1],
			["U_B_HeliPilotCoveralls", 1],
			["U_B_PilotCoveralls", 1],
			["U_B_SpecopsUniform_sgg", 1],
			["U_C_Novak", 1],
			["U_I_CombatUniform", 1],
			["U_I_CombatUniform_shortsleeve", 1],
			["U_I_CombatUniform_tshirt", 1],
			["U_I_GhillieSuit", 1],
			["U_I_HeliPilotCoveralls", 1],
			["U_I_OfficerUniform", 1],
			["U_I_pilotCoveralls", 1],
			["U_I_Wetsuit", 1],
			["U_IG_Menelaos", 1],

			["U_B_Wetsuit", 1],
			["U_BasicBody", 1],
			["U_C_Commoner1_1", 1],
			["U_C_Commoner1_2", 1],
			["U_C_Commoner1_3", 1],
			["U_C_Poloshirt_blue", 1],
			["U_C_Poloshirt_burgundy", 1],
			["U_C_Poloshirt_redwhite", 1],
			["U_C_Poloshirt_salmon", 1],
			["U_C_Poloshirt_stripped", 1],
			["U_C_Poloshirt_tricolour", 1],
			["U_OI_CombatUniform_ocamo", 1],
			["U_OI_PilotCoveralls", 1],
			["U_OI_Wetsuit", 1],
			["V_HarnessO_brn", 1],
			["U_Rangemaster", 1],
			////Vests
			["V_BandollierB_cbr", 1],
			["V_BandollierB_khk", 1],
			["V_BandollierB_oli", 1],
			["V_BandollierB_rgr", 1],

			["V_Chestrig_khk", 1], 	
			["V_ChestrigF_oli", 1],
			["V_ChestrigB_rgr", 1],

			["V_HarnessO_brn", 1],
			["V_HarnessOGL_brn", 1],
			["V_HarnessOGL_gry", 1],
			["V_HarnessOSpec_brn", 1],
			["V_HarnessOSpec_gry", 1],

			["V_PlateCarrier1_blk", 1],
			["V_PlateCarrier1_cbr", 1],
			["V_PlateCarrier1_rgr", 1],
			["V_PlateCarrier2_blk", 1],
			["V_PlateCarrier2_cbr", 1],
			["V_PlateCarrier2_rgr", 1],
			["V_PlateCarrierGL_blk", 1],
			["V_PlateCarrierGL_cbr", 1],
			["V_PlateCarrierGL_rgr", 1],
			["V_PlateCarrierIA1_dgtl", 1],
			["V_PlateCarrierIA2_dgtl", 1],
			["V_PlateCarrierIAGL_dgtl", 1],
			["V_PlateCarrierSpec_cbr", 1],
			["V_PlateCarrierSpec_rgr", 1],
			["V_Rangemaster_belt", 1],
			["V_RebreatherB", 1],
			["V_RebreatherIR", 1],
			["V_TacVest_blk", 1],
			["V_TacVest_blk_POLICE", 1],
			["V_TacVest_brn", 1],
			["V_TacVest_camo", 1],
			["V_TacVest_khk", 1],
			["V_TacVest_oli", 1],
			["V_TacVestCamo_khk", 1],
			["V_TacVestIR_blk", 1]

		]
	];
	
player sideChat "Loading Definitions Complete.";
